// 身份模式 AI 选将「按评分」权重数据；生成工具：_others/迁移工具/port-ai-weights.mjs（重新运行会覆盖本文件）。
// 源：_others/太阳神备份/太阳神三国杀V2.0 移植参照/etc/{loyalist,rebel,renegade}.txt
//     （太阳神版手工标定的 AI 选将权重表）。
//
// 语义（沿用太阳神 GeneralSelector 口径）：
//   - GENERIC[身份][候选]         —— 源表 `_ 候选 权重` 通用条目；
//   - BY_LORD[身份][主公][候选]   —— 源表 `主公 候选 权重` 专属条目；
//   - 评分 = GENERIC + BY_LORD 叠加（排序等价于源公式的 1.1^(w1+w2)）。
// 身份：zhong=忠臣（loyalist）/ fan=反贼（rebel）/ nei=内奸（renegade）。
// 键已归一化为「小写、无 st_/max_ 前缀」，别名 jizi→himiko（姬子）；表未收录得 0 分，
// 主公（zhu）位无表数据（另用启发式评分，见 characterPick.js）。
export const GENERIC = {
    zhong: {
        nakexia: 0.5,
        welt: 0.5,
        danheng: 0.5,
        fuxuan: 0.5,
        sanyueqi: 0.4,
        luocha: 0.4,
        bailu: 0.4,
        jialahe: 0.4,
        lingsha: 0.3,
        fengjin: 0.3,
        lingke: 0.2,
        sangbo: 0.1,
        saifeier: 0.1,
        agelaiya: 0.1,
        ren: 0.1,
        yaoguang: -0.1,
        huohua: -0.1,
        yinlang_lv999: -0.1,
        feiying: -0.1,
        shajin_xilang: -0.1,
        baie: -0.5,
        xilian: -0.5,
        ren_qianye: -0.7,
        wandi: -3,
        heitiane: -3,
    },
    fan: {
        ren: 1.2,
        liuying: 1.1,
        liuxie: 0.3,
        gilgamesh: -0.2,
        xilian: -0.2,
    },
    nei: {
        liuying: 1.2,
        sanyueqi: 0.8,
        welt: 0.5,
        danheng: 0.2,
        ren: -0.5,
        busitu: -0.1,
    },
};

export const BY_LORD = {
    zhong: {
        kaituozhe: {
            jizi_qixing: 1,
            sanyueqi: 0.8,
            danheng_tenghuang: 0.3,
            shajin: 0.2,
        },
        danheng: {
            jizi_qixing: 1,
        },
        welt: {
            jizi_qixing: 1,
        },
        sanyueqi: {
            jizi_qixing: 1,
            shajin: 0.8,
            danheng_tenghuang: 0.7,
            kaituozhe: 0.6,
            yanqing: 0.6,
        },
        shajin: {
            sanyueqi: 0.8,
            yanqing: 0.3,
            kaituozhe: 0.2,
            danheng_tenghuang: 0.1,
        },
        danheng_tenghuang: {
            sanyueqi: 0.8,
            kaituozhe: 0.3,
            yanqing: 0.2,
            shajin: 0.1,
        },
        tingyun: {
            yukong: 0.7,
        },
        yukong: {
            tingyun: 0.7,
        },
        yanqing: {
            feixiao: 1.2,
            sanyueqi: 0.8,
            danheng_tenghuang: 0.3,
            shajin: 0.2,
        },
        tuopa: {
            feixiao: 1.2,
            jingyuan: 1.1,
            moze: 1,
            yunli: 0.9,
            kelala: 0.8,
            busitu: 0.7,
            xueyi: 0.6,
        },
        feixiao: {
            qingque: 1.2,
            moze: 1.2,
            jingyuan: 1.1,
            tuopa: 1.1,
            yanqing: 1,
            lingsha: 0.9,
            kelala: 0.8,
            yunli: 0.8,
            saifeier: 0.7,
            busitu: 0.6,
            xueyi: 0.6,
        },
        kelvdela: {
            baie: 1.2,
        },
        xingqiri: {
            baie: 1.2,
        },
        luanpo: {
            sangbo: 1.2,
            saifeier: 1.1,
            liuying: 1,
            botiou: 0.9,
        },
        botiou: {
            luanpo: 1,
        },
        baie: {
            kelvdela: 1.2,
            fengjin: 1.1,
            bailu: 1,
            jialahe: 0.9,
            luocha: 0.8,
            lingsha: 0.7,
            natasha: 0.6,
        },
        agelaiya: {
            busitu: 1.2,
            kafuka: 1,
            tingyun: 0.8,
            yukong: 0.7,
            xiluwa: 0.6,
        },
        ren: {
            huohuo: 1.2,
            fengjin: 1.1,
            bailu: 1,
            jialahe: 0.9,
            luocha: 0.8,
            lingsha: 0.7,
            natasha: 0.6,
        },
        wandi: {
            huohuo: 1.2,
            fengjin: 1.1,
            bailu: 1,
            jialahe: 0.9,
            luocha: 0.8,
            lingsha: 0.7,
            natasha: 0.6,
        },
        ren_qianye: {
            luocha: 1.2,
            bailu: 1.1,
            natasha: 1,
            fengjin: 0.9,
            lingsha: 0.8,
            jialahe: 0.7,
            huohuo: 0.6,
        },
        changyeyue: {
            fengjin: 1.2,
            bailu: 1.1,
            jialahe: 1,
            huohuo: 0.9,
            luocha: 0.8,
            lingsha: 0.7,
            natasha: 0.6,
        },
        xiadie: {
            fengjin: 1.2,
            changyeyue: 1.1,
            ren: 1,
            wandi: 0.9,
            bailu: 0.8,
            jialahe: 0.8,
            huohuo: 0.7,
            luocha: 0.7,
            lingsha: 0.6,
            natasha: 0.6,
        },
        fengjin: {
            xiadie: 1.2,
            ren: 1.1,
            bailu: 1,
            jialahe: 0.9,
            huohuo: 0.8,
            luocha: 0.7,
            lingsha: 0.6,
            natasha: 0.6,
        },
        xilian: {
            baie: 1.2,
            saifeier: 1.1,
            kelvdela: 1,
            nakexia: 0.9,
            agelaiya: 0.8,
            fengjin: 0.7,
            xiadie: 0.6,
            changyeyue: 0.5,
            wandi: 0.4,
            tibao: 0.3,
            haiseyin: 0.2,
            danheng_tenghuang: 0.1,
            liuying: 1.1,
            xingqiri: 0.9,
            zhigengniao_qingge: 0.7,
            jingliu: 0.6,
            huahuo: 0.2,
        },
        liuying: {
            dalihua: 1.2,
            tingyun_wangguiren: 0.8,
            himiko: 0.6,
        },
        dalihua: {
            liuying: 1.2,
            jizi_qixing: 0.8,
        },
        tingyun_wangguiren: {
            liuying: 1.2,
            jizi_qixing: 0.8,
        },
        himiko: {
            jizi_qixing: 1.2,
            liuying: 1.1,
            jiaoqiu: 1,
            aisida: 0.9,
            guinaifen: 0.8,
            huke: 0.7,
            yinlang: 0.6,
            haiseyin: 0.6,
            ren_qianye: 0.1,
        },
        huangquan: {
            jiaoqiu: 1.2,
            haiseyin: 1.2,
            yinlang: 1.1,
            sangbo: 1,
            aisida: 0.9,
            kafuka: 0.8,
            shajin_xilang: 0.7,
            saifeier: 0.6,
            tuopa: 0.4,
            guinaifen: 0.4,
            jiepade: 0.4,
            huke: 0.4,
            xiluwa: 0.3,
            yanqing: 0.3,
            ren_qianye: 0.1,
        },
        jiaoqiu: {
            huangquan: 1.2,
            kafuka: 0.8,
        },
        nakexia: {
            haiseyin: 1.2,
            yinlang: 1.1,
            jiaoqiu: 1,
            sangbo: 0.9,
            aisida: 0.8,
            kafuka: 0.7,
            shajin_xilang: 0.6,
            saifeier: 0.5,
            tuopa: 0.4,
            guinaifen: 0.4,
            jiepade: 0.4,
            huke: 0.4,
            xiluwa: 0.3,
            yanqing: 0.3,
            ren_qianye: 0.1,
        },
        heitiane: {
            jiaoqiu: 1.2,
            haiseyin: 1.1,
            sangbo: 1,
            yinlang: 0.9,
            aisida: 0.8,
            kafuka: 0.7,
            guinaifen: 0.6,
            huke: 0.5,
            xiluwa: 0.4,
            ren_qianye: 0.3,
        },
        kafuka: {
            jiaoqiu: 1.2,
            haiseyin: 1.1,
            sangbo: 1,
            heitiane: 0.9,
            aisida: 0.8,
            yinlang: 0.7,
            xiluwa: 0.6,
            guinaifen: 0.5,
            huke: 0.4,
        },
        haiseyin: {
            huangquan: 1.2,
            heitiane: 0.7,
        },
        busitu: {
            agelaiya: 1.2,
            kafuka: 1,
            tingyun: 0.8,
            yukong: 0.7,
            xiluwa: 0.6,
        },
        jizi_qixing: {
            danheng: 0.8,
            himiko: 0.7,
            welt: 0.6,
            sanyueqi: 0.5,
            kaituozhe: 0.4,
        },
        saber: {
            huohuo: 0.5,
            tingyun: 0.5,
        },
        yuanbanlin: {
            archer: 0.9,
            qingque: 0.9,
        },
        archer: {
            yuanbanlin: 0.9,
        },
        gilgamesh: {
            wandi: 1.2,
            liuying: 1.1,
            agelaiya: 1,
            xingqiri: 0.9,
            jingliu: 0.8,
            zhigengniao_qingge: 0.6,
            huahuo: 0.3,
        },
        yaoguang: {
            xuzhao: 0.9,
            huohua: 0.8,
            zhenzhu: 0.7,
            qingque: 0.5,
            yinlang_lv999: 0.4,
            feiying: 0.3,
            shajin_xilang: 0.2,
        },
        huohua: {
            xuzhao: 0.9,
            yaoguang: 0.8,
            zhenzhu: 0.7,
            yinlang_lv999: 0.6,
            qingque: 0.5,
            feiying: 0.3,
            shajin_xilang: 0.2,
        },
        yinlang_lv999: {
            xuzhao: 0.9,
            huohua: 0.8,
            zhenzhu: 0.7,
            yaoguang: 0.6,
            qingque: 0.5,
            feiying: 0.3,
            shajin_xilang: 0.2,
        },
        feiying: {
            xuzhao: 0.9,
            huohua: 0.8,
            zhenzhu: 0.7,
            yaoguang: 0.6,
            qingque: 0.5,
            yinlang_lv999: 0.4,
            shajin_xilang: 0.2,
        },
        shajin_xilang: {
            moze: 1,
            xuzhao: 0.9,
            huohua: 0.8,
            zhenzhu: 0.7,
            yaoguang: 0.6,
            feicui: 0.6,
            yinlang_lv999: 0.5,
            qingque: 0.4,
            feiying: 0.3,
        },
        zhenzhu: {
            xuzhao: 0.9,
            huohua: 0.8,
            yaoguang: 0.7,
            qingque: 0.5,
            yinlang_lv999: 0.4,
            feiying: 0.3,
            shajin_xilang: 0.2,
        },
        xuzhao: {
            huohua: 0.8,
            zhenzhu: 0.7,
            yinlang_lv999: 0.6,
            yaoguang: 0.5,
            qingque: 0.4,
            feiying: 0.3,
            shajin_xilang: 0.2,
        },
    },
    fan: {
        sanyueqi: {
            tibao: 1.2,
        },
        danheng_tenghuang: {
            tibao: 1.2,
        },
        shajin: {
            tibao: 1.2,
        },
        yanqing: {
            tibao: 1.2,
        },
        kaituozhe: {
            tibao: 0.6,
        },
        agelaiya: {
            yunli: 1.2,
            kelala: 1.2,
            saber: 1.2,
            kaituozhe: 1,
            sanyueqi: 0.8,
            nakexia: 0.7,
            archer: 0.6,
            danheng: 0.6,
            liuying: 0.6,
            xier: 0.6,
            daheita: 0.6,
        },
        tibao: {
            sanyueqi: -1,
            danheng_tenghuang: -1,
            shajin: -1,
            yanqing: -1,
            kaituozhe: -1,
        },
    },
    nei: {},
};
